
export const EndPoints = {
    LoginAPI : "/user/login",
    CreateCompanyAPI : '/company/create',
    OTPAPI : '/user/verifyOtp',
    JoinCompanyAPI : '/company/join' ,
    UpdateUserAPI : '/user/updateUser',
    GetUser : '/user/profile',
    Logout : '/user/logOut',
    QualityCreate : '/quality/create',
    GetQualityData : '/quality/getall',
    UpdateQualityData : '/quality/update',
    GetPendignRequest : '/request-user/pending',
    GetYarnData : '/yarn/getall',
    GetCompanyData : '/yarn-company/getall',
    GetYarn : '/yarn/get',
    YarnDataUpdate : '/yarn/update',
    AddYarnData : '/yarn/create',
    AddYarnCompany : '/yarn-company/create',
    GetYarnQualityData : '/quality/getall',
    GetYarnActivity :  '/yarn-activity/getall',
    CreateCompany : '/company/create',
    GetProfile : '/user/profile',
    GetCurrentUser : '/request-user/current',
    RemoveRequest : '/request-user/removeUser',
    ProceedRequest : '/request-user/reqProceed',
    UpdateCurrentUser : '/request-user/update'
}
