export default {
    next : "Next",
    Name : "Name",
    Save : "Save",
    Done : "Done",
    EnterPhoneNumber : "Enter your\nMobile number",
    ConfirmationCode : "We will send you a confirmation code",
    EnterCompanyName : "Please enter your company name",
    Lorem : 'Lorem Ipsum is simply dummy text',
    Create_Company : "Create Company",
    EnterCompanyCode : 'Please enter your company code',
    Join_Company : "Join Company",
    Select_preference : "Select any of\nthese preference",
    Choose_Categories : "Please choose your desire categories",
    Add_Company : "Add Company",
    EnterName : "Enter Name",
    EnterCode : "Enter Code",
    Enter_Phone_Number : "Enter Phone Number" ,
    Enter_Company_Name : "Enter Company Name",
    EnterAddress : "Enter Address",
    KG : "kg",
    ruppes : "₹",
    Tar : "Tar",
    Width : "Width",
    Pick : "Pick",
    Gsm : "Gsm",
    Weft : "Weft",
    Warp : "Warp",
    Add_Quality : 'Add Quality',
    Quality_Details : "Quality Details",
    ANDROID : 'android',
    Camera_Permission : 'Camera Permission',
    AskMeLater : 'Ask Me Later',
    CANCEL : 'Cancel',
    OK : "OK",
    Weight : "Weight",
    Cost : "Cost",
    Detail : "Detail",
    Per_Pick : "Per Pick",
    Fixed_Cost : 'Fixed Cost',
    GRANTED : 'granted',
    Expense : "Expense",
    Production : "Production",
    MD : "m/d",
    RPM : "RPM",
    Efficiency : "Efficiency",
    Machine : "Machine",
    Labour : "Labour",
    Information : "Information",
    Reed : "Reed",
    Panno : "Panno",
    Border : "Border",
    Nozzle : "Nozzle",
    Pasramani : 'Pasramani',
    Lattice : "Lattice",
    Steam_Warp : 'Steam (warp)',
    Steam_Weft : 'Steam (weft)',
    Photos : "Photos",
    Sample : "Sample",
    Lattice_Pattern : 'Lattice Pattern',
    Pick_Pattern : "Pick Pattern",
    Pasramani_Pattern : "Pasramani Pattern",
    Image : "Image",
    Pdf : "Pdf",
    Camera : "Camera",
    Gallery : "Gallery",
    Status : "Status",
    SignOut : "Sign Out",
    Logout : "Logout",
    SureLogout : 'Are you sure, do you want to logout?',
    Account : "Account",
    Welcome_back : "Welcome back",
    YES : "Yes",
    NO : "No"
}